FROM ubuntu:22.04

RUN apt update && apt install -y \
    python3 \
    git \
    python3-pip \
    build-essential \
    pkg-config \
    cmake \
    && python3 -m pip install --upgrade pip

WORKDIR /app

ADD requirements.txt requirements.txt
ADD main.py main.py
ADD src src

RUN python3 -m pip install -r requirements.txt

CMD ["python3", "./main.py"]
